### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by andywhardy** [jonnylaw/ComposableStateSpaceModels#10]
This does not compile.

`sbt compile`

**Result**

`[error] /Users/nah230/work/ncl/github/jonnylaw/ComposableStateSpaceModels/src/main/scala/com/github/jonnylaw/examples/DetermineParameters.scala:79: type mismatch;
[error]  found   : akka.stream.scaladsl.Flow[com.github.jonnylaw.model.MetropState[com.github.jonnylaw.model.Parameters,com.github.jonnylaw.model.State],com.github.jonnylaw.model.MetropState[com.github.jonnylaw.model.Parameters,com.github.jonnylaw.model.State],akka.NotUsed]
[error]     (which expands to)  akka.stream.scaladsl.Flow[com.github.jonnylaw.model.MetropState[com.github.jonnylaw.model.Tree[com.github.jonnylaw.model.ParamNode],com.github.jonnylaw.model.Tree[breeze.linalg.DenseVector[Double]]],com.github.jonnylaw.model.MetropState[com.github.jonnylaw.model.Tree[com.github.jonnylaw.model.ParamNode],com.github.jonnylaw.model.Tree[breeze.linalg.DenseVector[Double]]],akka.NotUsed]
[error]  required: akka.stream.Graph[akka.stream.FlowShape[com.github.jonnylaw.model.MetropState[com.github.jonnylaw.model.Tree[com.github.jonnylaw.model.ParamNode],com.github.jonnylaw.model.StateSpace[com.github.jonnylaw.model.Tree[breeze.linalg.DenseVector[Double]]]],?],?]
[error]         via(Streaming.monitorStateStream).async.
[error]                       ^
[error] /Users/nah230/work/ncl/github/jonnylaw/ComposableStateSpaceModels/src/main/scala/com/github/jonnylaw/examples/Filtering.scala:68: value sde is not a member of com.github.jonnylaw.model.MetropState[com.github.jonnylaw.model.Parameters,com.github.jonnylaw.model.State]
[error]     simPosterior = Streaming.createDist(posterior)(x => (x.sde.state, x.params))
[error]                                                            ^
[error] /Users/nah230/work/ncl/github/jonnylaw/ComposableStateSpaceModels/src/main/scala/com/github/jonnylaw/examples/Filtering.scala:72: value sample is not a member of Any
[error]       via(ParticleFilter.filterOnline(resample, t0, 1000, simPosterior.sample(100).toVector, model)).
[error]                                                                        ^
[error] /Users/nah230/work/ncl/github/jonnylaw/ComposableStateSpaceModels/src/main/scala/com/github/jonnylaw/examples/Interpolate.scala:43: class PfOut takes type parameters
[error]       map((s: PfOut) => s.show).
[error]               ^
[error] four errors found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 32 s, completed 8 Nov 2019, 09:48:03`

**Comment by jonnylaw** [comment]
I'll take a look. It is worth noting that this compilation error does not affect the Sonatype release.

**Comment by jonnylaw** [comment]
I've updated the project to Scala 2.13 and resolved the compilation error.
